version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - mlnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - mlnet
    environment:
      - API_URL=http://backend:8000/predict   

networks:
  mlnet:
    driver: bridge
